### ISSUE TITLE
Tarea del módulo 1.1

### ISSUE THREAD

**Issue by IvorAcevedo** [SistemasTecTlaxiaco/cursogithubivor#1]
Teniendo en cuenta lo que has aprendido sobre Git, ¿por qué querrías usar Git en tu salón de clases?

Es una herramienta interesante, que como docente considero me ayudaria a organizar la entrega y seguimiento de actividades por cada unidad de aprendizaje, identificando la forma en que van avanzando los jovenes y las mejoras que realicen a las observaciones marcadas.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
