### ISSUE TITLE
Asignación del módulo 1.2

### ISSUE THREAD

**Issue by IvorAcevedo** [SistemasTecTlaxiaco/cursogithubivor#2]
He agregado la captura de pantalla de la Asignación del Módulo 1.1 como referencia

![](https://user-images.githubusercontent.com/89807325/131413362-6bee2f38-245d-4d4b-8b1e-acdfc26d2162.png)

**Comment by IvorAcevedo** [comment]
![imagen](https://user-images.githubusercontent.com/89807325/131413362-6bee2f38-245d-4d4b-8b1e-acdfc26d2162.png)

**Comment by IvorAcevedo** [comment]
He agregado la captura de pantalla de la Asignación del Módulo 1.2 como referencia

**Comment by josealfredo79** [comment]
Bien hecho y revisado
